# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'bigproject-conn'
    subscriptionId: 'aec799d0-d788-4e61-ac0f-017b5ec3300a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'challenge-rg'
    location: 'Switzerland North'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/konradKulagaAVA/challengeproject-repo/main/CreateWebApp/azuredeploy.json'
    deploymentMode: 'Incremental'
    deploymentName: 'challengeDeployment'