---
- hosts: localhost
  collections:
   - azure.azcollection
  # Our main "tasks" block, to put all modules execution we need
  tasks:
  # Below, we are executing task named "Hello World Type Task".
  # That task will use "set_fact" module. This module set ansible variable.
  # More at: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/set_fact_module.html
  - name: Create Azure
    set_fact:
      my_super_important_variable: 'I love Ansible!'
  # Below, we are executing task named "Print varialbe".
  # That task will use "debug" module. This module is used to print messages - here we will print ansible variable.
  # More at: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
  - name: Print varialbe we just set
    debug:
      msg: '{{ my_super_important_variable }}'
      
  - name: Let's see who executed this ?
    debug:
      msg: 'I know your email! -> {{ executor_email }}'

  # - name: Install msrest python package
  #   ansible.builtin.pip:
  #     name: msrest

  # - name: Install msrestazure python package
  #   ansible.builtin.pip:
  #     name: msrestazure

  # - name: Install ansible[azure] python package
  #   ansible.builtin.pip:
  #     name: ansible[azure]

  # - name: Install azure.cli python package
  #   ansible.builtin.pip:
  #     name: azure.cli

  # - name: Install azure-storage-blob python package
  #   ansible.builtin.pip:
  #     name: azure-storage-blob

  # - name: Install azure-storage-file-share python package
  #   ansible.builtin.pip:
  #     name: azure-storage-file-share

  # - name: Install azure-storage-file-datalake python package
  #   ansible.builtin.pip:
  #     name: azure-storage-file-datalake

  # - name: Install azure-storage-queue python package
  #   ansible.builtin.pip:
  #     name: azure-storage-queue

  # - name: Install file python package
  #   ansible.builtin.pip:
  #     requirements: /home/vsts/work/1/s/CreateWebApp/playbooks/requirements.txt
  # - name: Install azure-cli-core python package
  #   ansible.builtin.pip:
  #     name: azure-cli-core

- name: Install collection azure.azcollection
  community.general.ansible_galaxy_install:
    type: collection
    name: azure.azcollection
            
  - name: createAzureDeploy
    azure_rm_deployment:
      resource_group: challenge-rg
      name: challengeDeployment
      template_link: 'https://raw.githubusercontent.com/konradKulagaAVA/challengeproject-repo/main/CreateWebApp/azuredeploy.json'
      subscription_id: aec799d0-d788-4e61-ac0f-017b5ec3300a  
      location: Switzerland North
    

    